### ISSUE TITLE
Story assets should also be deleted when an album is deleted

### ISSUE THREAD

**Issue by MichielLeyman** [Prisma/api#131]

**Comment by MichielLeyman** [comment]
Essentially the same as #122, use an event for this

**Comment by blueclock** [comment]
I'm going to close this for the moment because it needs to be reframed.

a User deleting on of their own Albums should have their story assets removed.

But default heritage should not be removed even if the default album has been deleted to prevent further use of the default album in prepopulations.

Stories refer back to the original heritage URL so we'd be deleting assets that people may like.

We may need  purge function in the heritage uploader so that is a mistake is made or if we must remove content for legal reason we can do so, but otherwise I think it's OK to leave old stories in an individual's collection of stories even if we no longer want to share then with new users
